"""empty message

Revision ID: d086a4e97593
Revises: 09cf1c658f10
Create Date: 2017-08-07 17:33:59.708695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd086a4e97593'
down_revision = '09cf1c658f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spiner', sa.Column('css', sa.Text(), nullable=True))
    op.add_column('spiner', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('spiner', sa.Column('rotation_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spiner', 'rotation_time')
    op.drop_column('spiner', 'image')
    op.drop_column('spiner', 'css')
    # ### end Alembic commands ###
